# Generated by Django 2.2.19 on 2021-04-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('sent', 'sent'), ('accepted', 'accepted')], max_length=8, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to_user', to='profiles.UserProfile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_from_user', to='profiles.UserProfile')),
            ],
            options={
                'verbose_name': 'Follow request',
                'verbose_name_plural': 'Follow requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
