# Generated by Django 2.2.19 on 2021-08-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('sent', 'sent'), ('accepted', 'accepted'), ('declined', 'declined')], max_length=8, null=True),
        ),
    ]
